services:
  - type: web
    name: k-ruoka-scraping-service
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn scraper:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
